In [44]:
import numpy as np
import pandas as pd
from numpy.linalg import eig
from scipy import sin 
from autograd import hessian, jacobian
from sklearn.preprocessing import LabelEncoder


In [7]:
size = 10
matrix = np.random.randn(size, size)
matrix

array([[-0.57280534,  0.90659583,  0.85061838, -0.13102313, -1.06150469,
         0.59779786,  0.31910993, -0.20723455,  0.7570776 ,  1.17824601],
       [-1.51304579, -0.65479893,  0.7818107 , -1.02558547,  1.39466067,
        -0.58667637,  0.03952322,  0.6461904 , -0.97387093, -0.35952665],
       [-0.96862246, -0.95514571,  0.46058242,  0.36774382,  0.4720752 ,
         0.17175621,  0.30038211,  0.02121813, -0.68153946, -0.44506852],
       [-0.34375978,  0.20764028,  0.56778221, -0.50408969, -1.43367842,
        -0.54822982,  0.34343863, -0.45319528,  0.61437762, -1.48268408],
       [ 0.13896957, -1.41290566,  0.11578246,  1.25322406, -0.72462044,
         0.55536706,  1.37277644, -0.67216259,  0.51346818,  0.17053174],
       [ 0.70900898, -2.21648862, -1.03448557, -0.68621888,  0.51338626,
         0.7333757 ,  2.06540652,  0.86806963, -0.26513442,  0.66588857],
       [-0.37771646,  0.99087475,  0.02044138, -0.2064514 , -0.44386176,
         0.53263333, -1.42449277,  0.17961712

In [8]:
inverse_matrix = np.linalg.inv(matrix)
inverse_matrix

array([[ 1.46119155e-01, -1.06493072e+00,  1.88982905e+00,
        -1.70708513e-03, -1.54124900e+00,  5.71433578e-02,
        -8.82162899e-01, -2.62983653e-01,  4.61999383e-01,
        -7.90060461e-02],
       [-2.05411541e-01,  4.65339859e-01, -1.36574819e+00,
        -7.88568287e-02,  7.98300541e-01, -3.67015908e-01,
         6.25695553e-01,  5.22907307e-01, -1.04940213e-01,
        -8.38111815e-02],
       [ 7.23050764e-01, -1.39997874e+00,  3.50496529e+00,
         1.16215280e-01, -2.40451932e+00,  8.01655780e-03,
        -1.40373866e+00, -4.28988197e-01,  6.26636215e-01,
        -6.25403617e-02],
       [-1.94310864e-01,  3.54789585e-01, -7.41786269e-01,
        -1.75463938e-01,  8.01278681e-01, -2.56880953e-01,
         3.10984696e-01,  1.62051876e-01,  2.99793065e-02,
         9.65729594e-02],
       [-2.05312050e-02, -1.03007979e+00,  1.99684925e+00,
        -1.83061891e-01, -1.34018773e+00, -1.13422382e-01,
        -7.37396118e-01,  1.03802536e-01,  7.12664248e-02,
        -1.

In [9]:
dot_product = np.dot(matrix, matrix.T)
dot_product

array([[ 5.48110261, -2.04091947, -1.31485729,  1.04996974,  0.8419592 ,
        -2.24912593, -0.61703947, -0.10100895, -0.71961491, -1.61089734],
       [-2.04091947,  8.16719841,  3.48088196, -0.67735121, -2.75773791,
         1.22071279,  1.19798584,  2.54904863, -3.67294148, -0.09114543],
       [-1.31485729,  3.48088196,  3.20352131, -0.22546426,  1.45467522,
         1.59297122,  0.27924914,  1.57874221, -0.44709841,  1.32921731],
       [ 1.04996974, -0.67735121, -0.22546426,  5.99290608,  0.66596157,
        -2.91775668,  0.12087411, -1.84851475, -0.26599235, -1.95351551],
       [ 0.8419592 , -2.75773791,  1.45467522,  0.66596157,  7.06214678,
         4.51501576, -4.16731737,  2.03255724,  3.83148061, -0.58035002],
       [-2.24912593,  1.22071279,  1.59297122, -2.91775668,  4.51501576,
        13.29113048, -4.93895727,  5.75641668,  4.68596577, -6.49860142],
       [-0.61703947,  1.19798584,  0.27924914,  0.12087411, -4.16731737,
        -4.93895727,  7.12809199, -4.38886711

In [14]:
values, vectors = eig(matrix)
print(values)
print(vectors)

[ 0.02933771+3.04043508j  0.02933771-3.04043508j -2.73679291+0.j
  0.8583062 +1.92288418j  0.8583062 -1.92288418j -1.12736041+1.55099443j
 -1.12736041-1.55099443j  1.56064205+0.j          0.21795557+0.j
 -1.36339568+0.j        ]
[[-0.08825977-0.18827471j -0.08825977+0.18827471j  0.51829862+0.j
   0.24298279-0.09993303j  0.24298279+0.09993303j -0.09043497-0.36492873j
  -0.09043497+0.36492873j -0.10288873+0.j          0.23110699+0.j
  -0.1291656 +0.j        ]
 [ 0.05730328-0.23540491j  0.05730328+0.23540491j  0.05040844+0.j
   0.10182177+0.34891546j  0.10182177-0.34891546j  0.077032  +0.0110549j
   0.077032  -0.0110549j   0.08739353+0.j         -0.17315428+0.j
  -0.21413928+0.j        ]
 [ 0.17963818+0.03017368j  0.17963818-0.03017368j  0.00979661+0.j
  -0.07456032+0.38287668j -0.07456032-0.38287668j  0.07259686-0.1222677j
   0.07259686+0.1222677j  -0.02229115+0.j          0.40017426+0.j
  -0.10210868+0.j        ]
 [-0.14365267+0.4216717j  -0.14365267-0.4216717j   0.21960164+0.j
  -0.018

In [72]:
def f(x):
    result = x*x
    return result

In [73]:
jacobian_function = jacobian(f)

In [74]:
hessian_function = hessian(f)

In [78]:
jacobian_matrix = jacobian_function(matrix)
jacobian_matrix

array([[[[10.96220523, -0.        , -0.        , ..., -0.        ,
          -0.        , -0.        ],
         [-0.        ,  0.        ,  0.        , ...,  0.        ,
          -0.        , -0.        ],
         [-0.        ,  0.        ,  0.        , ...,  0.        ,
          -0.        ,  0.        ],
         ...,
         [-0.        ,  0.        ,  0.        , ...,  0.        ,
           0.        ,  0.        ],
         [-0.        , -0.        , -0.        , ...,  0.        ,
           0.        , -0.        ],
         [-0.        , -0.        ,  0.        , ...,  0.        ,
          -0.        ,  0.        ]],

        [[ 0.        , -4.08183894, -0.        , ..., -0.        ,
          -0.        , -0.        ],
         [-0.        ,  0.        ,  0.        , ...,  0.        ,
          -0.        , -0.        ],
         [-0.        ,  0.        ,  0.        , ...,  0.        ,
          -0.        ,  0.        ],
         ...,
         [-0.        ,  0.        

In [76]:
hessian_matrix = hessian_function(matrix)
hessian_matrix

array([[[[[[2., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.]],

          ...,

          [[0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           [0., 0., 0., ..., 0., 0., 0.],
           ...,
           [0., 0., 0., ..., 0.,

In [1]:
def load_df(file):
    """Loads the Dataset"""
    df = pd.read_csv(file)
    return df

def find_categorical_columns(df):
    """Returns name of Columns with string values"""
    categorical_columns = []
    for col in df.columns:
        if type(df[col][0]) == str:
            categorical_columns.append(col)
    return categorical_columns

def encode_columns(df):
    """Apply Encoding to columns"""
    columns = find_categorical_columns(df)
    encoder = LabelEncoder()
    df1 = df.copy()
    for column in columns:
        df1[column] = encoder.fit_transform(df1[column])
    return df1


In [87]:
path = 'diabetes_data_upload.csv'
df = load_df(path)
df

Age  Gender Polyuria Polydipsia sudden weight loss weakness Polyphagia  \
0     40    Male       No        Yes                 No      Yes         No   
1     58    Male       No         No                 No      Yes         No   
2     41    Male      Yes         No                 No      Yes        Yes   
3     45    Male       No         No                Yes      Yes        Yes   
4     60    Male      Yes        Yes                Yes      Yes        Yes   
..   ...     ...      ...        ...                ...      ...        ...   
515   39  Female      Yes        Yes                Yes       No        Yes   
516   48  Female      Yes        Yes                Yes      Yes        Yes   
517   58  Female      Yes        Yes                Yes      Yes        Yes   
518   32  Female       No         No                 No      Yes         No   
519   42    Male       No         No                 No       No         No   

    Genital thrush visual blurring Itching Irritability delayed healing  \
0               No              No     Yes           No             Yes   
1               No             Yes      No           No              No   
2               No              No     Yes           No             Yes   
3              Yes              No     Yes           No             Yes   
4               No             Yes     Yes          Yes             Yes   
..             ...             ...     ...          ...             ...   
515             No              No     Yes           No             Yes   
516             No              No     Yes          Yes             Yes   
517             No             Yes      No           No              No   
518             No             Yes     Yes           No             Yes   
519             No              No      No           No              No   

    partial paresis muscle stiffness Alopecia Obesity     class  
0                No              Yes      Yes     Yes  Positive  
1               Yes               No      Yes      No  Positive  
2                No              Yes      Yes      No  Positive  
3                No               No       No      No  Positive  
4               Yes              Yes      Yes     Yes  Positive  
..              ...              ...      ...     ...       ...  
515             Yes               No       No      No  Positive  
516             Yes               No       No      No  Positive  
517             Yes              Yes       No     Yes  Positive  
518              No               No      Yes      No  Negative  
519              No               No       No      No  Negative  

[520 rows x 17 columns]

In [88]:
df = encode_columns(df)
df

Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0     40       1         0           1                   0         1   
1     58       1         0           0                   0         1   
2     41       1         1           0                   0         1   
3     45       1         0           0                   1         1   
4     60       1         1           1                   1         1   
..   ...     ...       ...         ...                 ...       ...   
515   39       0         1           1                   1         0   
516   48       0         1           1                   1         1   
517   58       0         1           1                   1         1   
518   32       0         0           0                   0         1   
519   42       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  1                0                 1         1        1   
1                  0                1                 0         1        0   
2                  1                0                 1         1        0   
3                  1                0                 0         0        0   
4                  1                1                 1         1        1   
..               ...              ...               ...       ...      ...   
515                1                1                 0         0        0   
516                1                1                 0         0        0   
517                0                1                 1         0        1   
518                1                0                 0         1        0   
519                0                0                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      1  
516      1  
517      1  
518      0  
519      0  

[520 rows x 17 columns]

In [89]:
df['Age'] = df['Age'] /df['Age'].abs().max()
df


Age  Gender  Polyuria  Polydipsia  sudden weight loss  weakness  \
0    0.444444       1         0           1                   0         1   
1    0.644444       1         0           0                   0         1   
2    0.455556       1         1           0                   0         1   
3    0.500000       1         0           0                   1         1   
4    0.666667       1         1           1                   1         1   
..        ...     ...       ...         ...                 ...       ...   
515  0.433333       0         1           1                   1         0   
516  0.533333       0         1           1                   1         1   
517  0.644444       0         1           1                   1         1   
518  0.355556       0         0           0                   0         1   
519  0.466667       1         0           0                   0         0   

     Polyphagia  Genital thrush  visual blurring  Itching  Irritability  \
0             0               0                0        1             0   
1             0               0                1        0             0   
2             1               0                0        1             0   
3             1               1                0        1             0   
4             1               0                1        1             1   
..          ...             ...              ...      ...           ...   
515           1               0                0        1             0   
516           1               0                0        1             1   
517           1               0                1        0             0   
518           0               0                1        1             0   
519           0               0                0        0             0   

     delayed healing  partial paresis  muscle stiffness  Alopecia  Obesity  \
0                  1                0                 1         1        1   
1                  0                1                 0         1        0   
2                  1                0                 1         1        0   
3                  1                0                 0         0        0   
4                  1                1                 1         1        1   
..               ...              ...               ...       ...      ...   
515                1                1                 0         0        0   
516                1                1                 0         0        0   
517                0                1                 1         0        1   
518                1                0                 0         1        0   
519                0                0                 0         0        0   

     class  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
515      1  
516      1  
517      1  
518      0  
519      0  

[520 rows x 17 columns]

In [91]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1:]

In [ ]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.4)